language: python

os:
  - linux

python:
  - "2.7"
  - "3.7"

install:
  - sudo apt-get install libmpfr-dev
  - sudo apt-get install libmpc-dev
  - sudo apt-get install libgmp3-dev
  - pip install -r requirements.txt

script:
  - ls -a
  - sh test.sh
